"""replace_explanations_with_key_concepts

Revision ID: 14cd9e90595e
Revises: 2d607aa5dbae
Create Date: 2025-05-25 12:33:11.216937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cd9e90595e'
down_revision: Union[str, None] = '2d607aa5dbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_concepts',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('file_id', sa.Integer(), sa.ForeignKey('files.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('concept_title', sa.String(), nullable=False),
        sa.Column('concept_explanation', sa.Text(), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=True, default=0),
        sa.Column('source_page_number', sa.Integer(), nullable=True),
        sa.Column('source_video_timestamp_start_seconds', sa.Integer(), nullable=True),
        sa.Column('source_video_timestamp_end_seconds', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now(), nullable=True)
    )
    op.drop_table('explanations')
    op.drop_column('files', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('explanations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True),
        sa.Column('file_id', sa.Integer(), sa.ForeignKey('files.id', ondelete='CASCADE'), autoincrement=False, nullable=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), autoincrement=False, nullable=True),
        sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('page', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('video_start', sa.Float(), autoincrement=False, nullable=True),
        sa.Column('video_end', sa.Float(), autoincrement=False, nullable=True),
        sa.Column('selection_type', sa.String(), autoincrement=False, nullable=False),
        sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True)
    )
    op.drop_table('key_concepts')
    # ### end Alembic commands ###
