"""baseline migration

Revision ID: 1ab07ff317db
Revises: 
Create Date: 2025-09-09 19:58:21.105632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '1ab07ff317db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_files_processing_status'), 'files', ['processing_status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('concept_title', sa.String(length=500), nullable=False),
    sa.Column('concept_explanation', sa.Text(), nullable=False),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('source_video_timestamp_start_seconds', sa.Integer(), nullable=True),
    sa.Column('source_video_timestamp_end_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.CheckConstraint('source_video_timestamp_end_seconds IS NULL OR source_video_timestamp_start_seconds IS NULL OR source_video_timestamp_end_seconds >= source_video_timestamp_start_seconds', name='check_video_timestamps_valid'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_concepts_created_at'), 'key_concepts', ['created_at'], unique=False)
    op.create_index(op.f('ix_key_concepts_file_id'), 'key_concepts', ['file_id'], unique=False)
    op.create_index(op.f('ix_key_concepts_id'), 'key_concepts', ['id'], unique=False)
    op.create_index(op.f('ix_key_concepts_is_custom'), 'key_concepts', ['is_custom'], unique=False)
    op.create_index(op.f('ix_key_concepts_source_page_number'), 'key_concepts', ['source_page_number'], unique=False)
    op.create_index(op.f('ix_key_concepts_source_video_timestamp_start_seconds'), 'key_concepts', ['source_video_timestamp_start_seconds'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_history_id'], ['chat_histories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('key_concept_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_concept_id'], ['key_concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('key_concept_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('distractors', sa.JSON(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("question_type IN ('MCQ', 'true_false', 'short_answer')", name='check_question_type_valid'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_concept_id'], ['key_concepts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_created_at'), 'quiz_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_questions_file_id'), 'quiz_questions', ['file_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_is_custom'), 'quiz_questions', ['is_custom'], unique=False)
    op.create_index(op.f('ix_quiz_questions_key_concept_id'), 'quiz_questions', ['key_concept_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_question_type'), 'quiz_questions', ['question_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_questions_question_type'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_key_concept_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_is_custom'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_file_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_created_at'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_table('flashcards')
    op.drop_table('chunks')
    op.drop_table('segments')
    op.drop_table('messages')
    op.drop_index(op.f('ix_key_concepts_source_video_timestamp_start_seconds'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_source_page_number'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_is_custom'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_id'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_file_id'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_created_at'), table_name='key_concepts')
    op.drop_table('key_concepts')
    op.drop_table('card_details')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_files_processing_status'), table_name='files')
    op.drop_table('files')
    op.drop_table('chat_histories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
