"""Add summary column to files table

Revision ID: 21c6be8c491b
Revises: c78a7f7d0c86
Create Date: 2025-04-07 15:42:38.783634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c6be8c491b'
down_revision: Union[str, None] = 'c78a7f7d0c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'summary')
    # ### end Alembic commands ###
