"""Update subscriptions schema to allow no sub id

Revision ID: 8f470e6250f0
Revises: 925a4be8d0fe
Create Date: 2025-01-24 15:20:42.755727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f470e6250f0'
down_revision: Union[str, None] = '925a4be8d0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'segments', ['id'])
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_subscriptions_stripe_subscription_id', table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'segments', type_='unique')
    # ### end Alembic commands ###
