"""Add workspace model and file size tracking

Revision ID: b2d181e6791f
Revises: 0153f5c38158
Create Date: 2025-11-21 18:24:48.471725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d181e6791f'
down_revision: Union[str, None] = '0153f5c38158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw')
    op.drop_index('idx_chunks_file_id', table_name='chunks')
    op.add_column('files', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.drop_index('idx_files_user_id', table_name='files')
    op.create_foreign_key(None, 'files', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_index('idx_files_user_id', 'files', ['user_id'], unique=False)
    op.drop_column('files', 'file_size_bytes')
    op.drop_column('files', 'workspace_id')
    op.create_index('idx_chunks_file_id', 'chunks', ['file_id'], unique=False)
    op.create_index('idx_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
