"""make flashcard key_concept_id nullable

Revision ID: b3f6f949b5af
Revises: 20250617_add_ps
Create Date: 2025-06-23 15:24:56.225787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f6f949b5af'
down_revision: Union[str, None] = '20250617_add_ps'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'key_concept_id', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'key_concept_id', nullable=False)
    # ### end Alembic commands ###
