"""Add is_custom column and standardize flashcard/quiz models

Revision ID: bae9d2d5f0f8
Revises: 8f9d76ee9391
Create Date: 2025-06-23 16:02:20.119218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bae9d2d5f0f8'
down_revision: Union[str, None] = '8f9d76ee9391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'processing_status',
               existing_type=postgresql.ENUM('uploaded', 'extracting', 'extracted', 'processing', 'processed', 'failed', name='file_processing_status'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::file_processing_status"))
    op.drop_index('idx_files_processing_status', table_name='files')
    op.create_index(op.f('ix_files_processing_status'), 'files', ['processing_status'], unique=False)
    op.alter_column('flashcards', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('flashcards', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flashcards', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flashcards', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('quiz_questions', sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('quiz_questions', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quiz_questions', 'is_custom')
    op.alter_column('flashcards', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('flashcards', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flashcards', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flashcards', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_files_processing_status'), table_name='files')
    op.create_index('idx_files_processing_status', 'files', ['processing_status'], unique=False)
    op.alter_column('files', 'processing_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('uploaded', 'extracting', 'extracted', 'processing', 'processed', 'failed', name='file_processing_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::file_processing_status"))
    # ### end Alembic commands ###
