"""Update KeyConcept and QuizQuestion models with relationships and constraints

Revision ID: bf6c68ecaeed
Revises: d19d37cdae20
Create Date: 2025-08-21 16:21:02.185603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6c68ecaeed'
down_revision: Union[str, None] = 'd19d37cdae20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_key_concepts_created_at'), 'key_concepts', ['created_at'], unique=False)
    op.create_index(op.f('ix_key_concepts_is_custom'), 'key_concepts', ['is_custom'], unique=False)
    op.create_index(op.f('ix_key_concepts_source_page_number'), 'key_concepts', ['source_page_number'], unique=False)
    op.create_index(op.f('ix_key_concepts_source_video_timestamp_start_seconds'), 'key_concepts', ['source_video_timestamp_start_seconds'], unique=False)
    op.add_column('quiz_questions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('quiz_questions', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_quiz_questions_created_at'), 'quiz_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_questions_file_id'), 'quiz_questions', ['file_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_is_custom'), 'quiz_questions', ['is_custom'], unique=False)
    op.create_index(op.f('ix_quiz_questions_key_concept_id'), 'quiz_questions', ['key_concept_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_question_type'), 'quiz_questions', ['question_type'], unique=False)
    op.drop_constraint('quiz_questions_key_concept_id_fkey', 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'key_concepts', ['key_concept_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key('quiz_questions_key_concept_id_fkey', 'quiz_questions', 'key_concepts', ['key_concept_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_quiz_questions_question_type'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_key_concept_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_is_custom'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_file_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_created_at'), table_name='quiz_questions')
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('quiz_questions', 'updated_at')
    op.drop_index(op.f('ix_key_concepts_source_video_timestamp_start_seconds'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_source_page_number'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_is_custom'), table_name='key_concepts')
    op.drop_index(op.f('ix_key_concepts_created_at'), table_name='key_concepts')
    # ### end Alembic commands ###
