"""Add trial_end column to subscriptions

Revision ID: c78a7f7d0c86
Revises: ce83804fe17a
Create Date: 2025-02-06 10:25:08.287158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78a7f7d0c86'
down_revision: Union[str, None] = 'ce83804fe17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('trial_end', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'trial_end')
    # ### end Alembic commands ###
