"""Add is_custom field to key_concepts table

Revision ID: d396200e75c3
Revises: bae9d2d5f0f8
Create Date: 2025-07-07 12:51:24.949519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd396200e75c3'
down_revision: Union[str, None] = 'bae9d2d5f0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column only if it does not already exist (idempotent)
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name='key_concepts' AND column_name='is_custom'
            ) THEN
                ALTER TABLE key_concepts ADD COLUMN is_custom BOOLEAN NOT NULL DEFAULT FALSE;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_concepts', 'is_custom')
    # ### end Alembic commands ###
