"""Add is_custom field to key_concepts table

Revision ID: d396200e75c3
Revises: bae9d2d5f0f8
Create Date: 2025-07-07 12:51:24.949519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd396200e75c3'
down_revision: Union[str, None] = 'bae9d2d5f0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_concepts', sa.Column('is_custom', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_concepts', 'is_custom')
    # ### end Alembic commands ###
