name: syntext-app

services:
  - name: frontend
    git:
      repo: https://github.com/Sarsue/SynTextAI.git
      branch: main
    build_command: npm run build
    run_command: serve -s build -l 80  # Assuming you use `serve` to serve static files
    source_dir: frontend
    static_site:
      build_dir: build
    envs:
      - key: REACT_APP_API_BASE_URL
        value: ${REACT_APP_API_BASE_URL}  # Reference global env variable

  - name: backend
    git:
      repo: https://github.com/Sarsue/SynTextAI.git
      branch: main
    run_command: gunicorn app:create_app --bind 0.0.0.0:5000
    source_dir: backend
    environment_slug: python-3.8
    envs:
      - key: DATABASE_URL
        value: ${DATABASE_URL}  # Reference global env variable
      - key: SECRET_KEY
        value: ${SECRET_KEY}  # Reference global env variable
    routes:
      - path: /api/v1/
