name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Only trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t osasdeeon/syntextai:latest .
          docker push osasdeeon/syntextai:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script: |
            cd /home/root/app
            docker pull osasdeeon/syntextai:latest
            docker stop $(docker ps -q) || true
            docker run -d --env-file .env -p 3000:3000 osasdeeon/syntextai:latest
            systemctl restart nginx
