version: '3.8'

services:
  frontend:
    image: osasdeeon/syntext:docsynth-frontend
    ports:
      - "80:3000"
    env_file:
      - .env

  backend:
    image: osasdeeon/syntext:docsynth-backend
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - ./backend/db:/app/db
    command: gunicorn app:create_app --bind 0.0.0.0:5000
