version: '3.8'

services:
  syntextaiapp:
    image: osasdeeon/syntextai:latest
    container_name: syntextaiapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_SSLROOTCERT=/app/api/config/ca-certificate.crt
    volumes:
      - ./api/config:/app/api/config
      - ./.env:/app/.env
    networks:
      - syntextai_network
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

  worker:
    image: osasdeeon/syntextai:latest
    container_name: syntextai-worker
    command: sh -c "export PYTHONPATH=/app && python -m api.worker"
    env_file:
      - .env
    environment:
      - MAX_CONCURRENT_TASKS=3
      - POLL_INTERVAL=10
      - PYTHONPATH=/app
      - DATABASE_SSLROOTCERT=/app/api/config/ca-certificate.crt
    volumes:
      - ./api/config:/app/api/config
      - ./.env:/app/.env
    networks:
      - syntextai_network
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped


networks:
  syntextai_network:
    driver: bridge
