"""
Quiz Agent for generating and managing quizzes and flashcards from content.

This module provides the QuizAgent class which is responsible for generating
interactive quizzes and flashcards from document content in the SynTextAI system.
It supports multiple question types, difficulty levels, and integrates with the
files API to generate and store assessment materials.

Key Features:
- Generates multiple question types (MCQ, True/False, short answer)
- Creates various flashcard formats (basic, MCQ, true/false)
- Supports configurable difficulty levels
- Includes detailed explanations for answers
- Tracks source content and key concepts for each question
- Integrates with the database for persistent storage

Example Usage:
    ```python
    # Initialize the agent
    agent = QuizAgent()
    
    # Generate quiz questions
    quiz_result = await agent.process({
        "action": "generate_questions",
        "file_id": 123,
        "file_content": "Content to generate questions from...",
        "count": 5,
        "difficulty": "medium",
        "question_types": ["MCQ", "true_false"]
    })
    
    # Generate flashcards
    flashcard_result = await agent.process({
        "action": "generate_flashcards",
        "file_id": 123,
        "count": 10,
        "flashcard_types": ["basic", "mcq"]
    })
    
    # Access the results
    questions = quiz_result.get("questions", [])
    flashcards = flashcard_result.get("flashcards", [])
    ```
"""
from typing import Dict, Any, List, Optional, cast
import json
import logging
import random
from pydantic import BaseModel, Field, validator

# Import agent decorator from agent_factory
from .agent_factory import agent

# Import repository manager
from ..repositories import get_repository_manager
from ..repositories.async_learning_material_repository import AsyncLearningMaterialRepository

from .base_agent import BaseAgent, AgentConfig
from .prompt_loader import PromptLoader
from ..services.llm_service import llm_service
from ..models.orm_models import KeyConcept

logger = logging.getLogger(__name__)

class QuizConfig(AgentConfig):
    """
    Configuration for the Quiz Agent.
    
    This configuration class controls how the QuizAgent generates quizzes and flashcards,
    including question types, difficulty levels, and output formats.
    
    Attributes:
        max_flashcards: Maximum number of flashcards to generate in a single request.
                      Range: 1-50
                      Default: 10
        flashcard_types: Types of flashcards to generate. Each type has different formats:
                       - 'basic': Simple Q&A format
                       - 'mcq': Multiple-choice questions
                       - 'true_false': True/False statements
                       Default: ["basic", "mcq", "true_false"]
        num_questions: Number of quiz questions to generate per request.
                     Range: 1-20
                     Default: 5
        difficulty: Difficulty level of generated questions.
                  One of: "easy", "medium", "hard"
                  Default: "medium"
        question_types: Types of quiz questions to generate.
                      Supported types: "MCQ", "true_false", "short_answer"
                      Default: ["MCQ", "true_false", "short_answer"]
        include_explanations: Whether to include detailed explanations for answers.
                            Default: True
    """
    max_flashcards: int = Field(
        default=10,
        description="Maximum number of flashcards to generate in a single request",
        ge=1,
        le=50
    )
    flashcard_types: List[str] = Field(
        default_factory=lambda: ["basic", "mcq", "true_false"],
        description="Types of flashcards to generate (basic, mcq, true_false)",
        example=["basic", "mcq"]
    )
    num_questions: int = Field(
        default=5,
        description="Number of questions to generate per quiz",
        ge=1,
        le=20
    )
    difficulty: str = Field(
        default="medium",
        description="Difficulty level of the quiz questions",
        enum=["easy", "medium", "hard"]
    )
    question_types: List[str] = Field(
        default_factory=lambda: ["MCQ", "true_false", "short_answer"],
        description="Types of questions to include in the quiz",
        example=["MCQ", "true_false"]
    )
    include_explanations: bool = Field(
        default=True,
        description="Whether to include explanations for the correct answers"
    )

class QuizQuestion(BaseModel):
    """
    Model representing a single quiz question or flashcard.
    
    This model defines the structure of assessment items generated by the QuizAgent.
    It's designed to be compatible with both the database schema and frontend expectations.
    
    Attributes:
        question: The question text or flashcard front side.
        question_type: Type of question/flashcard. One of: "MCQ", "true_false", "short_answer".
                     Default: "MCQ"
        options: List of answer choices (for MCQ questions).
               Aliased as 'distractors' for backward compatibility.
        correct_answer: The correct answer to the question.
        explanation: Detailed explanation of the correct answer.
        difficulty: Difficulty level ("easy", "medium", "hard").
                  Default: "medium"
        key_concept_id: Optional reference to the related key concept in the database.
        source_page: Page number in the source document (for PDFs).
        source_text: The original text from which the question was generated.
    """
    question: str = Field(..., description="The question text or flashcard front side")
    question_type: str = Field(
        default="MCQ",
        description="Type of question/flashcard (MCQ, true_false, short_answer)",
        example="MCQ"
    )
    options: List[str] = Field(
        default_factory=list,
        alias="distractors",
        description="List of answer choices (for MCQ questions)"
    )
    correct_answer: str = Field(..., description="The correct answer to the question")
    explanation: str = Field(
        default="",
        description="Detailed explanation of the correct answer"
    )
    difficulty: str = Field(
        default="medium",
        description="Difficulty level (easy, medium, hard)",
        example="medium"
    )
    key_concept_id: Optional[int] = Field(
        default=None,
        description="Reference to the related key concept in the database"
    )
    source_page: Optional[int] = Field(
        default=None,
        description="Page number in the source document (for PDFs)"
    )
    source_text: Optional[str] = Field(
        default=None,
        description="Original text from which the question was generated"
    )
    
    class Config:
        allow_population_by_field_name = True
        
    @validator('question_type')
    def validate_question_type(cls, v):
        valid_types = ["MCQ", "true_false", "short_answer", "multiple_choice"]
        if v.lower() not in [t.lower() for t in valid_types]:
            raise ValueError(f"Invalid question type. Must be one of: {', '.join(valid_types)}")
        # Standardize to uppercase for consistency
        return v.upper() if v.upper() in ["MCQ", "TRUE_FALSE"] else v.lower()

class QuizResult(BaseModel):
    """Model representing a complete quiz."""
    title: str
    description: str
    questions: List[QuizQuestion]
    total_questions: int
    estimated_time_minutes: int

@agent(
    "quiz",
    config={
        "max_flashcards": 10,
        "flashcard_types": ["basic", "mcq", "true_false"],
        "num_questions": 5,
        "difficulty": "medium",
        "question_types": ["MCQ", "true_false", "short_answer"],
        "include_explanations": True
    },
    description="Generates quizzes and flashcards from educational content",
    version="1.0.0",
    input_schema={
        "type": "object",
        "properties": {
            "action": {"type": "string", "enum": ["generate_questions", "generate_flashcards"]},
            "file_id": {"type": "integer"},
            "file_content": {"type": "string"},
            "key_concepts": {"type": "array", "items": {"type": "object"}},
            "count": {"type": "integer", "minimum": 1, "maximum": 20},
            "difficulty": {"type": "string", "enum": ["easy", "medium", "hard"]},
            "question_types": {"type": "array", "items": {"type": "string"}},
            "flashcard_types": {"type": "array", "items": {"type": "string"}}
        },
        "required": ["action", "file_id"]
    },
    output_schema={
        "type": "object",
        "properties": {
            "questions": {"type": "array", "items": {"type": "object"}},
            "flashcards": {"type": "array", "items": {"type": "object"}}
        }
    }
)
class QuizAgent(BaseAgent[QuizConfig]):
    """
    Agent for generating and managing quizzes and flashcards from content.
    
    The QuizAgent is a core component of SynTextAI that transforms educational
    content into interactive assessment materials. It supports multiple question
    formats, difficulty levels, and integrates with the system's key concept
    framework to create pedagogically sound assessments.
    
    Key Features:
    - Generates multiple question types (MCQ, True/False, short answer)
    - Creates various flashcard formats (basic, MCQ, true/false)
    - Supports configurable difficulty levels
    - Includes detailed explanations for answers
    - Tracks source content and key concepts
    - Integrates with the database for persistent storage
    
    The agent follows a two-step process:
    1. Extracts key concepts from the content (or uses provided ones)
    2. Generates assessment items based on the concepts and configuration
    
    Example:
        ```python
        # Initialize with custom configuration
        config = QuizConfig(
            num_questions=10,
            difficulty="hard",
            question_types=["MCQ", "true_false"],
            max_flashcards=20,
            flashcard_types=["basic", "mcq"]
        )
        agent = QuizAgent(config)
        
        # Generate quiz questions
        quiz_result = await agent.process({
            "action": "generate_questions",
            "file_id": 123,
            "file_content": "Educational content...",
            "count": 5,
            "difficulty": "medium"
        })
        
        # Generate flashcards
        flashcard_result = await agent.process({
            "action": "generate_flashcards",
            "file_id": 123,
            "count": 10
        })
        ```
    """
    
    @classmethod
    def get_default_config(cls) -> QuizConfig:
        """Return the default configuration for this agent."""
        return QuizConfig()
    
    async def process(self, input_data: Dict[str, Any], db: Optional[Any] = None) -> Dict[str, Any]:
        """
        Process quiz or flashcard generation request.
        
        Expected input format for quizzes:
        {
            "action": "generate_questions",
            "file_id": int,  # Required for database lookup
            "file_content": str,
            "key_concepts": Optional[List[Dict]],  # Will be fetched from DB if not provided
            "count": int,
            "difficulty": str,
            "question_types": List[str]
        }
        
        Expected input format for flashcards:
        {
            "action": "generate_flashcards",
            "file_id": int,  # Required for database lookup
            "key_concepts": Optional[List[Dict]],  # Will be fetched from DB if not provided
            "count": int,
            "flashcard_types": List[str]  # basic, mcq, true_false
        }
        
        Args:
            input_data: Dictionary containing input parameters
            db: Optional repository manager (kept for backward compatibility but not used)
            
        Returns:
            Dictionary containing the generated questions in the format expected by the frontend
        """
        action = input_data.get("action", "generate_questions").lower()
        
        try:
            if action == "generate_questions":
                return await self._generate_quiz_questions(input_data)
            elif action == "generate_flashcards":
                return await self._generate_flashcards(input_data)
            else:
                raise ValueError(f"Unknown action: {action}")
                
        except Exception as e:
            logger.error(f"Error in QuizAgent: {str(e)}", exc_info=True)
            return {
                "status": "error",
                "error": str(e)
            }
    
    async def _prepare_prompt(self, input_data: Dict[str, Any]) -> str:
        """Prepare the prompt for the LLM.
        
        Args:
            input_data: Dictionary containing the input data for the prompt
            
        Returns:
            Formatted prompt string with key concepts from the database
            
        Note:
            If key_concepts are provided in input_data, they'll be used directly.
            Otherwise, key concepts will be fetched from the database.
        """
        # Use provided key concepts or fetch from database
        if "key_concepts" in input_data and input_data["key_concepts"]:
            key_concepts = input_data["key_concepts"]
        else:
            if "file_id" not in input_data:
                raise ValueError("file_id is required when key_concepts are not provided")
                
            # Get repository manager and learning material repository
            repo_manager = await get_repository_manager()
            learning_material_repo = await repo_manager.learning_material_repo
            
            # Fetch key concepts from the database
            key_concepts_data = await learning_material_repo.get_key_concepts_by_file_id(input_data["file_id"])
            key_concepts = [
                {
                    "concept": kc.concept,
                    "definition": kc.definition,
                    "examples": kc.examples
                }
                for kc in key_concepts_data
            ]
        
        # Format the key concepts for the prompt
        formatted_concepts = []
        for concept in key_concepts:
            formatted_concept = f"- {concept['concept']}"
            if concept.get('definition'):
                formatted_concept += f"\n  Definition: {concept['definition']}"
            if concept.get('examples'):
                formatted_concept += f"\n  Examples: {concept['examples']}"
            formatted_concepts.append(formatted_concept)
        
        # Get the prompt template based on the action
        action = input_data.get("action", "generate_questions").lower()
        if action == "generate_questions":
            prompt_template = self.prompt_loader.get_prompt("quiz_generation")
        elif action == "generate_flashcards":
            prompt_template = self.prompt_loader.get_prompt("flashcard_generation")
        else:
            raise ValueError(f"Unknown action: {action}")
        
        # Format the prompt with the content and key concepts
        prompt = prompt_template.format(
            content=input_data.get("file_content", ""),
            key_concepts="\n".join(formatted_concepts),
            count=input_data.get("count", 5),
            difficulty=input_data.get("difficulty", "medium"),
            question_types=", ".join(input_data.get("question_types", ["MCQ"]))
        )
        
        return prompt
    
    async def _generate_quiz_questions(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """Generate quiz questions from content."""
        # Prepare the prompt with content and key concepts
        prompt = await self._prepare_prompt(input_data)
        
        # Call the LLM to generate questions
        response = await self._call_llm(prompt)
        
        # Parse and validate the response
        result = self._parse_llm_response(response)
        
        # Add metadata
        result.update({
            "file_id": input_data.get("file_id"),
            "generated_at": datetime.utcnow().isoformat(),
            "config": self.config.dict()
        })
        
        return result
    
    async def _generate_flashcards(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """Generate flashcards from key concepts."""
        file_id = input_data.get("file_id")
        if not file_id:
            raise ValueError("file_id is required for flashcard generation")
            
        # Update config from input data if provided
        if "count" in input_data:
            self.config.max_flashcards = input_data["count"]
        if "flashcard_types" in input_data:
            self.config.flashcard_types = input_data["flashcard_types"]
            
        # Get key concepts from input or database
        key_concepts = input_data.get("key_concepts")
        if key_concepts is None:
            # Get repository manager and learning material repository
            repo_manager = await get_repository_manager()
            learning_material_repo = await repo_manager.learning_material_repo
            
            # Fetch key concepts from the database
            key_concepts_data = await learning_material_repo.get_key_concepts_by_file_id(file_id)
            key_concepts = [
                {
                    "concept": kc.concept,
                    "definition": kc.definition,
                    "examples": kc.examples
                }
                for kc in key_concepts_data
            ]
        
        if not key_concepts:
            return {
                "status": "success",
                "flashcards": [],
                "message": "No key concepts found for flashcard generation"
            }
            
        # Generate flashcards
        flashcards = []
        for concept in key_concepts[:self.config.max_flashcards]:
            if "basic" in self.config.flashcard_types:
                flashcards.append(self._generate_basic_flashcard(concept))
            if "mcq" in self.config.flashcard_types and len(key_concepts) > 1:
                flashcards.append(self._generate_mcq_flashcard(concept, key_concepts))
            if "true_false" in self.config.flashcard_types and len(key_concepts) > 1:
                flashcards.append(self._generate_true_false_flashcard(concept, key_concepts))
        
        return {
            "status": "success",
            "flashcards": flashcards,
            "file_id": file_id
        }
    
    async def _get_key_concepts_from_db(self, file_id: int) -> List[Dict[str, Any]]:
        """Fetch key concepts from the database for a given file."""
        try:
            # Get repository manager and learning material repository
            repo_manager = await get_repository_manager()
            learning_material_repo = await repo_manager.learning_material_repo
            
            # Fetch key concepts from the database
            concepts = await learning_material_repo.get_key_concepts_by_file_id(file_id)
            
            # Convert to list of dictionaries
            return [
                {
                    "concept": c.concept,
                    "definition": c.definition,
                    "examples": c.examples,
                    "page_number": c.page_number,
                    "created_at": c.created_at.isoformat() if c.created_at else None
                }
                for c in concepts
            ]
            
        except Exception as e:
            logger.error(f"Error fetching key concepts from database: {str(e)}")
            return []
    
    def _generate_basic_flashcard(self, concept: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a basic Q&A flashcard from a key concept with practical application."""
        # Check if there are related concepts in the explanation
        explanation = concept.get("concept_explanation", "")
        related_concepts_section = "Related Concepts:"
        
        if related_concepts_section in explanation:
            # Split to get the main explanation and related concepts
            main_explanation = explanation.split(related_concepts_section)[0].strip()
            related_concepts = explanation.split(related_concepts_section)[1].strip()
            
            # Create a practical application question
            question = f"How would you apply {concept['concept_title']} in a real-world scenario?"
            
            return {
                "type": "practical",
                "question": question,
                "answer": main_explanation,
                "related_concepts": related_concepts,
                "key_concept_id": concept.get("id"),
                "source_page": concept.get("source_page"),
                "source_timestamp_start": concept.get("source_timestamp_start"),
                "source_timestamp_end": concept.get("source_timestamp_end")
            }
        else:
            # Fallback to basic flashcard if no related concepts
            return {
                "type": "basic",
                "question": f"What is {concept['concept_title']}?",
                "answer": explanation,
                "key_concept_id": concept.get("id"),
                "source_page": concept.get("source_page"),
                "source_timestamp_start": concept.get("source_timestamp_start"),
                "source_timestamp_end": concept.get("source_timestamp_end")
            }
    
    def _generate_mcq_flashcard(self, concept: Dict[str, Any], all_concepts: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate a multiple-choice flashcard from a key concept with adaptive questions."""
        explanation = concept.get("concept_explanation", "")
        related_concepts_section = "Related Concepts:"
        
        if related_concepts_section in explanation:
            # For concepts with relationships, create application-based questions
            main_explanation = explanation.split(related_concepts_section)[0].strip()
            related_concepts = explanation.split(related_concepts_section)[1].strip()
            
            # Create an application-based question
            question = f"Which of the following scenarios best demonstrates the application of {concept['concept_title']}?"
            
            # Generate realistic but incorrect application scenarios
            distractors = []
            for other_concept in all_concepts:
                if other_concept.get("id") != concept.get("id"):
                    # Create plausible but incorrect application scenarios
                    distractor = (
                        f"A situation where {other_concept.get('concept_title', 'this concept')} "
                        f"is used instead of {concept['concept_title']}"
                    )
                    distractors.append(distractor)
                    if len(distractors) >= 3:  # Limit number of distractors
                        break
            
            # Add one correct application scenario
            correct_scenario = (
                f"A situation where {concept['concept_title']} is applied to solve "
                f"a specific problem in its intended context"
            )
            options = distractors + [correct_scenario]
            random.shuffle(options)
            
            return {
                "type": "application_mcq",
                "question": question,
                "options": options,
                "correct_answer": correct_scenario,
                "explanation": f"The correct answer demonstrates a proper application of {concept['concept_title']}: {main_explanation}",
                "key_concept_id": concept.get("id"),
                "source_page": concept.get("source_page"),
                "source_timestamp_start": concept.get("source_timestamp_start"),
                "source_timestamp_end": concept.get("source_timestamp_end")
            }
        else:
            # Fallback to basic MCQ for concepts without relationships
            correct_answer = concept["concept_explanation"]
            distractors = [
                c["concept_explanation"] 
                for c in all_concepts 
                if c.get("id") != concept.get("id")
            ]
            random.shuffle(distractors)
            distractors = distractors[:2]  # Use 2 distractors
            options = distractors + [correct_answer]
            random.shuffle(options)
            
            return {
                "type": "mcq",
                "question": f"Which of the following best describes '{concept['concept_title']}'?",
                "options": options,
                "correct_answer": correct_answer,
                "key_concept_id": concept.get("id"),
                "source_page": concept.get("source_page"),
                "source_timestamp_start": concept.get("source_timestamp_start"),
                "source_timestamp_end": concept.get("source_timestamp_end")
            }
    
    def _generate_true_false_flashcard(self, concept: Dict[str, Any], all_concepts: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate a true/false flashcard that tests understanding of concept relationships."""
        explanation = concept.get("concept_explanation", "")
        related_concepts_section = "Related Concepts:"
        
        if related_concepts_section in explanation:
            # For concepts with relationships, create relationship-based true/false questions
            main_explanation = explanation.split(related_concepts_section)[0].strip()
            related_concepts = explanation.split(related_concepts_section)[1].strip()
            
            # Randomly decide whether to create a true or false statement
            is_true = random.choice([True, False])
            
            if is_true:
                # Create a true statement about the concept's relationships
                relationship_phrases = [
                    f"is related to",
                    f"can be used together with",
                    f"is often combined with",
                    f"shares characteristics with"
                ]
                relationship = random.choice(relationship_phrases)
                
                # Extract the first related concept
                first_related = related_concepts.split('\n')[0].split(':')[0].strip()
                statement = f"{concept['concept_title']} {relationship} {first_related}"
            else:
                # Create a false statement by using an unrelated concept
                unrelated_concepts = [
                    c for c in all_concepts 
                    if c.get("id") != concept.get("id") and 
                       c["concept_title"] not in related_concepts
                ]
                
                if unrelated_concepts:
                    unrelated = random.choice(unrelated_concepts)
                    relationship_phrases = [
                        f"is the same as",
                        f"is a type of",
                        f"is completely unrelated to",
                        f"cannot be used with"
                    ]
                    relationship = random.choice(relationship_phrases)
                    statement = f"{concept['concept_title']} {relationship} {unrelated['concept_title']}"
                else:
                    # Fallback to basic true/false if no unrelated concepts
                    statement = concept["concept_explanation"]
                    is_true = True
            
            return {
                "type": "relationship_tf",
                "question": f"True or False: {statement}",
                "correct_answer": is_true,
                "explanation": (
                    f"This statement is {'true' if is_true else 'false'}. "
                    f"{main_explanation}"
                ),
                "key_concept_id": concept.get("id"),
                "source_page": concept.get("source_page"),
                "source_timestamp_start": concept.get("source_timestamp_start"),
                "source_timestamp_end": concept.get("source_timestamp_end")
            }
        else:
            # Fallback to basic true/false for concepts without relationships
            use_true = random.choice([True, False])
            
            if use_true or len(all_concepts) == 1:
                statement = concept["concept_explanation"]
                is_true = True
            else:
                # Pick a random explanation from another concept
                distractors = [c for c in all_concepts if c.get("id") != concept.get("id")]
                if distractors:
                    distractor = random.choice(distractors)
                    statement = distractor["concept_explanation"]
                    is_true = False
                else:
                    statement = concept["concept_explanation"]
                    is_true = True
            
            return {
                "type": "true_false",
                "question": f"True or False: '{concept['concept_title']}' is defined as: {statement}",
                "correct_answer": is_true,
                "key_concept_id": concept.get("id"),
                "source_page": concept.get("source_page"),
                "source_timestamp_start": concept.get("source_timestamp_start"),
                "source_timestamp_end": concept.get("source_timestamp_end")
            }
    
    def _parse_llm_response(self, response: str) -> List[QuizQuestion]:
        """Parse and validate the LLM response for quiz questions."""
        try:
            # Parse JSON response
            data = json.loads(response)
            
            # Basic validation
            if not isinstance(data, dict):
                raise ValueError("Invalid response format: expected JSON object")
                
            if "questions" not in data or not isinstance(data["questions"], list):
                raise ValueError("Invalid response format: missing or invalid 'questions' field")
            
            questions = []
            for i, q_data in enumerate(data["questions"], 1):
                try:
                    # Convert question data to QuizQuestion model
                    # This will validate the data structure
                    question = QuizQuestion(**q_data)
                    questions.append(question)
                except Exception as e:
                    logger.warning(f"Skipping invalid question {i}: {str(e)}")
                    continue
            
            if not questions:
                raise ValueError("No valid questions found in the response")
                
            return questions
            
        except json.JSONDecodeError as e:
            raise ValueError(f"Failed to parse LLM response: {str(e)}") from e
